package com.jc.intelligence.contract.v1.validation;

public enum IntelligenceValidationErrorCode {
    INTELLIGENCE_CONTRACT_ID_INVALID,
    INTELLIGENCE_ENTITY_REF_INVALID,
    INTELLIGENCE_SUBJECT_REF_INVALID,
    INTELLIGENCE_REFERENCE_INVALID,
    INTELLIGENCE_VERSION_INVALID,
    INTELLIGENCE_TIME_RANGE_INVALID,
    INTELLIGENCE_HASH_INVALID,
    INTELLIGENCE_RUN_STATUS_INVALID,
    INTELLIGENCE_REPLAY_CLASS_INVALID,
    INTELLIGENCE_SNAPSHOT_INVALID,
    INTELLIGENCE_FEATURE_INVALID,
    INTELLIGENCE_EXPLANATION_INVALID,
    INTELLIGENCE_INFERENCE_INVALID,
    INTELLIGENCE_ENUM_VALUE_INVALID,
    INTELLIGENCE_PRIVACY_CLASS_INVALID
}
