package com.jc.intelligence.contract.v1.search.validation;

public enum SearchValidationErrorCode {
    SEARCH_QUERY_BLANK,
    SEARCH_QUERY_TOO_LONG,
    SEARCH_QUERY_UNSUPPORTED_CHARACTER,
    SEARCH_FILTER_INVALID,
    SEARCH_SORT_INVALID,
    SEARCH_CURSOR_INVALID,
    SEARCH_CURSOR_EXPIRED,
    SEARCH_CURSOR_MISMATCH,
    SEARCH_VERSION_INVALID,
    SEARCH_POLICY_VERSION_INVALID,
    SEARCH_NULL_INVALID,
    SEARCH_REQUEST_INVALID,
    SEARCH_RANK_INVALID,
    SEARCH_SCORE_INVALID,
    SEARCH_FINGERPRINT_INVALID,
    SEARCH_ENUM_INVALID,
    SEARCH_REFERENCE_INVALID,
    SEARCH_RUN_STATUS_INVALID,
    SEARCH_REPLAY_CLASS_INVALID
}
