import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (relative) => fs.readFileSync(path.join(ROOT, relative), "utf8");
const app = read("App.jsx");
const guard = read("admin/AdminRouteGuard.jsx");
const dashboard = read("pages/admin/AdminDashboardPage.jsx");
const reports = read("pages/admin/AdminReportsPage.jsx");
const reportDetail = read("pages/admin/AdminReportDetailPage.jsx");
const posts = read("pages/admin/AdminPostsPage.jsx");
const postDetail = read("pages/admin/AdminPostDetailPage.jsx");
const users = read("pages/admin/AdminUsersPage.jsx");
const userDetail = read("pages/admin/AdminUserDetailPage.jsx");
const dialog = read("admin/AdminCommandDialog.jsx");
const api = read("services/adminApi.js");

const named = (name, condition) => test(name, () => assert.ok(condition));

named("anonymous_admin_route_redirects_or_blocks", guard.includes('<Navigate to="/login"'));
named("normal_user_admin_route_is_forbidden", guard.includes('state.status === "forbidden"'));
named("admin_user_can_enter_admin_route", guard.includes('status: "allowed"'));
named("direct_admin_url_refresh_is_supported", app.includes('path="reports/:reportId"') && app.includes('path="posts/:postId"') && app.includes('path="users/:userId"'));
named("standalone_admin_login_route_exists", app.includes('path="/login"') && app.includes("AdminLoginPage"));
named("dashboard_renders_four_summary_cards", dashboard.includes("dashboard?.totalUsers") && dashboard.includes("dashboard?.activePostCount") && dashboard.includes("dashboard?.pendingReportCount") && dashboard.includes("dashboard?.suspendedUserCount"));
named("recent_reports_are_limited", dashboard.includes("recentReports || []).slice(0, 5)"));
named("recent_actions_are_limited", dashboard.includes("recentAdminActions || []).slice(0, 5)"));
named("dashboard_empty_state_renders", dashboard.includes("AdminEmpty"));
named("dashboard_does_not_render_internal_fields", !/requestId|correlationId|SQLSTATE|databaseRole|functionName/.test(dashboard));
named("report_list_renders_pagination", reports.includes("AdminPagination"));
named("report_filters_are_sent_correctly", reports.includes('FILTERS = ["status", "targetType"]'));
named("report_detail_renders_allowed_fields", reportDetail.includes("currentTargetState") && reportDetail.includes("reasonDetail"));
named("resolve_requires_reason", reportDetail.includes("AdminCommandDialog") && api.includes("resolveAdminReport"));
named("dismiss_requires_reason", reportDetail.includes("AdminCommandDialog") && api.includes("dismissAdminReport"));
named("resolve_success_refreshes_state", reportDetail.includes("Promise.all([load(), refreshDashboard()])"));
named("same_state_changed_false_is_handled", reportDetail.includes("result.changed ?") && postDetail.includes("result.changed ?") && userDetail.includes("result.changed ?"));
named("report_conflict_shows_safe_message", read("admin/adminErrors.js").includes("현재 상태가 변경되어 요청을 처리할 수 없습니다."));
named("post_list_renders", posts.includes("data.items.map"));
named("post_detail_renders", postDetail.includes("contentPreview") && postDetail.includes("moderationStatus"));
named("hide_requires_reason", postDetail.includes('command === "hide"') && dialog.includes("required"));
named("restore_requires_reason", api.includes("restoreAdminPost") && postDetail.includes("AdminCommandDialog") && dialog.includes("required"));
named("hide_uses_hide_semantics_not_delete", api.includes("/hide") && !api.includes("delete"));
named("changed_false_is_handled", postDetail.includes("추가 변경 없이 완료되었습니다."));
named("physical_delete_action_does_not_exist", !/영구 삭제|완전 삭제|DB 삭제|deleteAdminPost/.test(`${posts}${postDetail}${api}`));
named("user_list_renders", users.includes("data.items.map"));
named("user_detail_renders", userDetail.includes("accountStatus") && userDetail.includes("suspendedAt"));
named("suspend_requires_reason", userDetail.includes('command === "suspend"') && dialog.includes("required"));
named("unsuspend_requires_reason", api.includes("unsuspendAdminUser") && userDetail.includes("AdminCommandDialog") && dialog.includes("required"));
named("role_change_control_does_not_exist", !/changeRole|역할 변경/.test(userDetail));
named("admin_appointment_control_does_not_exist", !/appointAdmin|관리자 임명|관리자 해제/.test(userDetail));
named("sensitive_fields_are_not_rendered", !/passwordHash|accessToken|refreshToken|jwtClaims|oauthRaw/.test(`${users}${userDetail}`));
named("401_is_handled", read("admin/adminErrors.js").includes("AUTHENTICATION_REQUIRED"));
named("403_is_handled", read("admin/adminErrors.js").includes("ADMIN_ACCESS_DENIED"));
named("404_is_handled", read("admin/adminErrors.js").includes("ADMIN_TARGET_NOT_FOUND"));
named("409_is_handled", read("admin/adminErrors.js").includes("ADMIN_STATE_CONFLICT"));
named("duplicate_submit_is_blocked", dialog.includes("if (pending) return") && dialog.includes("disabled={pending"));
named("loading_state_renders", read("admin/AdminUi.jsx").includes("AdminLoading"));
named("empty_state_renders", read("admin/AdminUi.jsx").includes("AdminEmpty"));
named("error_state_renders", read("admin/AdminUi.jsx").includes("AdminError"));
named("dialog_accessibility_baseline", dialog.includes('role="dialog"') && dialog.includes('aria-modal="true"') && dialog.includes("event.key === \"Escape\"") && dialog.includes("event.key !== \"Tab\""));
named("all_six_commands_are_connected", ["resolveAdminReport", "dismissAdminReport", "hideAdminPost", "restoreAdminPost", "suspendAdminUser", "unsuspendAdminUser"].every((name) => api.includes(`export const ${name}`)));
