package com.jc.recommendation.p2;

import com.jc.recommendation.p2.P2EvaluationContracts.*;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public final class P2CoreContractTest {
    private static final Instant FROM=Instant.parse("2026-07-01T00:00:00Z");
    private static final Instant TO=Instant.parse("2026-07-10T00:00:00Z");
    private static final P2EvaluationEngine ENGINE=new P2EvaluationEngine();
    private P2CoreContractTest(){}
    public static void main(String[] args){
        deterministic(); inputOrderIndependent(); livePromotion(); operationalApprovalRequired(); invalidTransitionHolds(); lowSampleHolds(); imbalanceFails(); missingMetricFails(); outOfWindowFails(); nonExposedExcluded(); lowerIsBetterGuardrail(); severeRegressionRollsBack(); lowSampleRegressionHolds(); moderateRegressionHolds(); segmentThresholdEnforced(); duplicateObservationRejected(); duplicateSubjectRejected(); duplicateMetricRejected(); mixedMetricVersionsRejected(); stateMachineContract(); fingerprintBindsDataset(); assignmentDeterministic(); assignmentBounds();
        System.out.println("P2 core contract: PASS (23 scenarios)");
    }
    private static void deterministic(){EvaluationInput in=passing("dataset:det",ReleaseState.SHADOW,ReleaseState.CANARY,true);require(ENGINE.evaluate(in).equals(ENGINE.evaluate(in)),"deterministic");}
    private static void inputOrderIndependent(){EvaluationInput in=passing("dataset:order",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<Observation> copy=new ArrayList<>(in.observations());Collections.reverse(copy);require(ENGINE.evaluate(in).fingerprint().equals(ENGINE.evaluate(copy(in,copy,in.metricDefinitions(),in.datasetSnapshotId())).fingerprint()),"order");}
    private static void livePromotion(){EvaluationResult r=ENGINE.evaluate(passing("dataset:live",ReleaseState.CANARY,ReleaseState.LIVE,true));require(r.finalDecision()==FinalDecision.LIVE&&r.targetState()==ReleaseState.LIVE,"live");}
    private static void operationalApprovalRequired(){EvaluationResult r=ENGINE.evaluate(passing("dataset:no-approval",ReleaseState.SHADOW,ReleaseState.CANARY,false));require(r.finalDecision()==FinalDecision.HOLD,"approval");}
    private static void invalidTransitionHolds(){EvaluationResult r=ENGINE.evaluate(passing("dataset:transition",ReleaseState.DRAFT,ReleaseState.LIVE,true));require(r.finalDecision()==FinalDecision.HOLD,"transition");}
    private static void lowSampleHolds(){EvaluationInput in=passing("dataset:sample",ReleaseState.SHADOW,ReleaseState.CANARY,true);EvaluationInput low=new EvaluationInput(in.evaluationRunId(),in.experimentId(),in.experimentVersion(),in.datasetSnapshotId(),in.datasetSchemaVersion(),in.baselinePolicyVersion(),in.treatmentPolicyVersion(),in.observedFrom(),in.observedTo(),in.evaluatedAt(),in.metricDefinitions(),in.observations().subList(0,8),in.evaluationPolicy(),in.currentState(),in.requestedState(),in.operationalApproval(),in.evaluatorBuildId());require(gate(ENGINE.evaluate(low),Gate.SAMPLE_SUFFICIENCY).status()==GateStatus.HOLD,"sample");}
    private static void imbalanceFails(){EvaluationInput in=passing("dataset:imbalance",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<Observation> list=in.observations().stream().filter(o->o.variant()==Variant.BASELINE||o.observationId().endsWith("-0")).toList();require(gate(ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())),Gate.DATA_QUALITY).status()==GateStatus.FAIL,"imbalance");}
    private static void missingMetricFails(){EvaluationInput in=passing("dataset:missing",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<Observation> list=new ArrayList<>(in.observations());for(int i=0;i<20;i++){Observation o=list.get(i);list.set(i,new Observation(o.observationId(),o.subjectRef(),o.segment(),o.variant(),o.assigned(),o.exposed(),o.eligible(),o.occurredAt(),Map.of("fallback_rate",0.01d)));}require(gate(ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())),Gate.DATA_QUALITY).status()==GateStatus.FAIL,"missing");}
    private static void outOfWindowFails(){EvaluationInput in=passing("dataset:window",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<Observation> list=new ArrayList<>(in.observations());Observation o=list.getFirst();list.set(0,new Observation(o.observationId(),o.subjectRef(),o.segment(),o.variant(),true,true,true,TO.plusSeconds(1),o.metricValues()));require(gate(ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())),Gate.DATA_QUALITY).status()==GateStatus.FAIL,"window");}
    private static void nonExposedExcluded(){EvaluationInput in=passing("dataset:exposed",ReleaseState.SHADOW,ReleaseState.CANARY,true);Observation o=in.observations().getFirst();List<Observation> list=new ArrayList<>(in.observations());list.set(0,new Observation(o.observationId(),o.subjectRef(),o.segment(),o.variant(),true,false,true,o.occurredAt(),o.metricValues()));MetricResult m=ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())).segments().getFirst().metrics().getFirst();require(m.eligibleExposedCount()==in.observations().size()-1,"exposed");}
    private static void lowerIsBetterGuardrail(){EvaluationResult r=ENGINE.evaluate(passing("dataset:lower",ReleaseState.SHADOW,ReleaseState.CANARY,true));MetricResult g=r.segments().getFirst().metrics().get(1);require(g.orientedEffect()>0,"lower");}
    private static void severeRegressionRollsBack(){EvaluationInput in=passing("dataset:rollback",ReleaseState.CANARY,ReleaseState.LIVE,true);List<Observation> list=in.observations().stream().map(o->new Observation(o.observationId(),o.subjectRef(),o.segment(),o.variant(),true,true,true,o.occurredAt(),Map.of("engagement_rate",o.metricValues().get("engagement_rate"),"fallback_rate",o.variant()==Variant.TREATMENT?0.9d:0.0d))).toList();EvaluationResult r=ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId()));require(r.finalDecision()==FinalDecision.ROLLBACK,"rollback");}
    private static void lowSampleRegressionHolds(){EvaluationInput in=passing("dataset:rollback-low-sample",ReleaseState.CANARY,ReleaseState.LIVE,true);List<Observation> list=in.observations().subList(0,8).stream().map(o->new Observation(o.observationId(),o.subjectRef(),o.segment(),o.variant(),true,true,true,o.occurredAt(),Map.of("engagement_rate",o.metricValues().get("engagement_rate"),"fallback_rate",o.variant()==Variant.TREATMENT?0.9d:0.0d))).toList();EvaluationResult r=ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId()));require(r.finalDecision()==FinalDecision.HOLD,"low sample rollback");}
    private static void moderateRegressionHolds(){EvaluationInput in=passing("dataset:guard",ReleaseState.CANARY,ReleaseState.LIVE,true);List<Observation> list=in.observations().stream().map(o->new Observation(o.observationId(),o.subjectRef(),o.segment(),o.variant(),true,true,true,o.occurredAt(),Map.of("engagement_rate",o.metricValues().get("engagement_rate"),"fallback_rate",o.variant()==Variant.TREATMENT?0.03d:0.0d))).toList();require(ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())).finalDecision()==FinalDecision.HOLD,"guard");}
    private static void segmentThresholdEnforced(){EvaluationInput in=passing("dataset:segment",ReleaseState.SHADOW,ReleaseState.CANARY,true);EvaluationPolicy p=new EvaluationPolicy("eval-policy-segment",20,100,0.8,0.95,300,2,0.05,0.1,0.05);EvaluationInput modified=new EvaluationInput(in.evaluationRunId(),in.experimentId(),in.experimentVersion(),in.datasetSnapshotId(),in.datasetSchemaVersion(),in.baselinePolicyVersion(),in.treatmentPolicyVersion(),in.observedFrom(),in.observedTo(),in.evaluatedAt(),in.metricDefinitions(),in.observations(),p,in.currentState(),in.requestedState(),true,in.evaluatorBuildId());require(gate(ENGINE.evaluate(modified),Gate.SAMPLE_SUFFICIENCY).status()==GateStatus.HOLD,"segment");}
    private static void duplicateObservationRejected(){EvaluationInput in=passing("dataset:dup-o",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<Observation> list=new ArrayList<>(in.observations());list.add(list.getFirst());expect(()->ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())));}
    private static void duplicateSubjectRejected(){EvaluationInput in=passing("dataset:dup-s",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<Observation> list=new ArrayList<>(in.observations());Observation o=list.getFirst();list.add(new Observation("extra",o.subjectRef(),o.segment(),Variant.TREATMENT,true,true,true,o.occurredAt(),o.metricValues()));expect(()->ENGINE.evaluate(copy(in,list,in.metricDefinitions(),in.datasetSnapshotId())));}
    private static void duplicateMetricRejected(){EvaluationInput in=passing("dataset:dup-m",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<MetricDefinition> defs=new ArrayList<>(in.metricDefinitions());defs.add(defs.getFirst());expect(()->ENGINE.evaluate(copy(in,in.observations(),defs,in.datasetSnapshotId())));}
    private static void mixedMetricVersionsRejected(){EvaluationInput in=passing("dataset:mixed",ReleaseState.SHADOW,ReleaseState.CANARY,true);List<MetricDefinition> defs=new ArrayList<>(in.metricDefinitions());MetricDefinition d=defs.get(1);defs.set(1,new MetricDefinition(d.metricId(),"metrics-v2",d.role(),d.direction(),d.minimumEffect(),d.maximumAllowedRegression(),d.attributionWindowSeconds(),d.numeratorDefinition(),d.denominatorDefinition(),d.eligibilityDefinition(),d.deduplicationDefinition()));expect(()->ENGINE.evaluate(copy(in,in.observations(),defs,in.datasetSnapshotId())));}
    private static void stateMachineContract(){P2ReleaseStateMachine m=new P2ReleaseStateMachine();require(m.canTransition(ReleaseState.DRAFT,ReleaseState.SHADOW)&&m.canTransition(ReleaseState.CANARY,ReleaseState.LIVE)&&!m.canTransition(ReleaseState.DRAFT,ReleaseState.LIVE),"state");}
    private static void fingerprintBindsDataset(){EvaluationInput a=passing("dataset:a",ReleaseState.SHADOW,ReleaseState.CANARY,true);EvaluationInput b=copy(a,a.observations(),a.metricDefinitions(),"dataset:b");require(!ENGINE.evaluate(a).fingerprint().equals(ENGINE.evaluate(b).fingerprint()),"fingerprint");}
    private static void assignmentDeterministic(){P2ExperimentAssigner a=new P2ExperimentAssigner();require(a.assign("recommendation-p1","experiment-v1","user:10",2500,"salt-v1").equals(a.assign("recommendation-p1","experiment-v1","user:10",2500,"salt-v1")),"assignment");}
    private static void assignmentBounds(){P2ExperimentAssigner a=new P2ExperimentAssigner();require(a.assign("recommendation-p1","experiment-v1","user:10",0,"salt-v1").variant()==Variant.BASELINE&&a.assign("recommendation-p1","experiment-v1","user:10",10000,"salt-v1").variant()==Variant.TREATMENT,"bounds");}
    private static EvaluationInput passing(String dataset,ReleaseState current,ReleaseState requested,boolean approval){return new EvaluationInput("evaluation:"+dataset.substring(dataset.indexOf(':')+1),"recommendation-p1","experiment-v1",dataset,"dataset-v1","ranking-policy-v1","p1-policy-bundle-v1:home_feed:empty",FROM,TO,TO.plusSeconds(1),definitions(),observations(),new EvaluationPolicy("eval-policy-v1",20,10,0.8,0.95,300,91337,0.05,0.1,0.05),current,requested,approval,"p2-evaluator-v1");}
    private static List<MetricDefinition> definitions(){return List.of(new MetricDefinition("engagement_rate","metrics-v1",MetricRole.PRIMARY,MetricDirection.HIGHER_IS_BETTER,0.1,0,604800,"engaged subjects","exposed subjects","assigned exposed eligible","one subject"),new MetricDefinition("fallback_rate","metrics-v1",MetricRole.GUARDRAIL,MetricDirection.LOWER_IS_BETTER,0,0.02,86400,"fallback runs","exposed runs","assigned exposed eligible","distinct runs"));}
    private static List<Observation> observations(){List<Observation> list=new ArrayList<>();for(Variant v:Variant.values())for(int i=0;i<40;i++)list.add(new Observation(v.wireValue()+"-"+i,"user:"+(v==Variant.BASELINE?i:100+i),i<20?"new":"established",v,true,true,true,FROM.plusSeconds(100+i),Map.of("engagement_rate",v==Variant.TREATMENT?0.9d:0.2d,"fallback_rate",v==Variant.TREATMENT?0.0d:0.01d)));return List.copyOf(list);}
    private static EvaluationInput copy(EvaluationInput in,List<Observation> obs,List<MetricDefinition> defs,String dataset){return new EvaluationInput(in.evaluationRunId(),in.experimentId(),in.experimentVersion(),dataset,in.datasetSchemaVersion(),in.baselinePolicyVersion(),in.treatmentPolicyVersion(),in.observedFrom(),in.observedTo(),in.evaluatedAt(),defs,obs,in.evaluationPolicy(),in.currentState(),in.requestedState(),in.operationalApproval(),in.evaluatorBuildId());}
    private static GateResult gate(EvaluationResult r,Gate g){return r.gates().stream().filter(x->x.gate()==g).findFirst().orElseThrow();}
    private static void require(boolean c,String m){if(!c)throw new AssertionError(m);}private static void expect(Runnable r){try{r.run();throw new AssertionError("expected failure");}catch(IllegalArgumentException expected){}}
}
